import { Router } from "express";
import PDFDocument from "pdfkit";
import { prisma } from "../../lib/prisma";
import { AppError } from "../../lib/errors";
import { asyncHandler } from "../../middleware/asyncHandler";
import { requireAuth } from "../../middleware/auth";
import { requirePropertyMember } from "../../middleware/propertyAccess";
import { getCurrentOwnership } from "../../utils/ownership";

export const pdfReportRouter = Router();
pdfReportRouter.use(requireAuth);

function money(n: number) {
  return `${n.toLocaleString("en-US", { maximumFractionDigits: 2 })} JOD`;
}

// GET /api/properties/:propertyId/reports/pdf?year=&month=
// A clean, official-looking monthly statement — free to generate (pdfkit,
// no external service), suitable for handing to a lawyer or keeping as a
// permanent record. Note: pdfkit's built-in fonts don't include Arabic
// glyphs, so this statement is produced in English/numeric form by design —
// still fully usable as an official reference document.
pdfReportRouter.get(
  "/:propertyId/reports/pdf",
  requirePropertyMember,
  asyncHandler(async (req, res) => {
    const { propertyId } = req.params;
    const year = Number(req.query.year) || new Date().getFullYear();
    const month = Number(req.query.month) || new Date().getMonth() + 1;

    const [property, ownership, closing, transactions] = await Promise.all([
      prisma.property.findUniqueOrThrow({ where: { id: propertyId } }),
      getCurrentOwnership(propertyId),
      prisma.monthlyClosing.findUnique({
        where: { propertyId_periodYear_periodMonth: { propertyId, periodYear: year, periodMonth: month } },
        include: { distribution: { include: { items: { include: { user: true } } } } },
      }),
      prisma.transaction.findMany({
        where: { propertyId, date: { gte: new Date(year, month - 1, 1), lt: new Date(year, month, 1) } },
        orderBy: { date: "asc" },
      }),
    ]);
    if (!property) throw AppError.notFound("العقار غير موجود.");

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="qisma-statement-${year}-${month}.pdf"`);
    doc.pipe(res);

    doc.fontSize(20).text("QISMA — Property Statement", { align: "center" });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor("#5F717A").text(`${property.name}${property.address ? " — " + property.address : ""}`, { align: "center" });
    doc.text(`Period: ${month}/${year}`, { align: "center" });
    doc.moveDown(1.5);
    doc.fillColor("#16202B");

    doc.fontSize(14).text("Ownership Structure");
    doc.moveDown(0.3);
    ownership.forEach((o) => {
      doc.fontSize(10).text(`${o.user.fullName} — ${o.sharePercent}%`);
    });
    doc.moveDown(1);

    doc.fontSize(14).text("Financial Summary");
    doc.moveDown(0.3);
    if (closing) {
      doc.fontSize(10);
      doc.text(`Reported income: ${money(closing.reportedIncome)}`);
      doc.text(`Verified income: ${money(closing.verifiedIncome)}`);
      doc.text(`Reported expenses: ${money(closing.reportedExpenses)}`);
      doc.text(`Verified expenses: ${money(closing.verifiedExpenses)}`);
      doc.font("Helvetica-Bold").text(`Net verified income: ${money(closing.netVerifiedIncome)}`);
      doc.font("Helvetica");
    } else {
      doc.fontSize(10).fillColor("#A8431F").text("This month has not been closed yet — figures below are unaudited.");
      doc.fillColor("#16202B");
    }
    doc.moveDown(1);

    doc.fontSize(14).text("Transactions");
    doc.moveDown(0.3);
    doc.fontSize(9);
    transactions.forEach((t) => {
      const sign = t.type === "INCOME" ? "+" : "-";
      doc.text(`${t.date.toISOString().slice(0, 10)}  ${t.category.padEnd(30)}  ${sign}${money(t.amount)}  [${t.status}]`);
    });
    if (transactions.length === 0) doc.text("No transactions recorded this period.");
    doc.moveDown(1);

    if (closing?.distribution) {
      doc.fontSize(14).text("Distribution");
      doc.moveDown(0.3);
      doc.fontSize(10);
      closing.distribution.items.forEach((item) => {
        doc.text(`${item.user.fullName} (${item.sharePercent}%): ${money(item.amount)} — ${item.paid ? "Paid" : "Pending"}`);
      });
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor("#94A3AB").text(`Generated by Qisma on ${new Date().toISOString().slice(0, 10)}. For reference purposes.`, {
      align: "center",
    });

    doc.end();
  })
);
